# 데이터 구조의 이해 (4) - Tensor
- pytorch installation: https://pytorch.org/get-started/locally/
1. cpu installation: `pip install torch torchvision torchaudio`
1. gpu instalation: `pip install` 또는 `conda install`로 OS, CUDA 버전에 맞게 설치

In [19]:
import torch
torch.__version__

'2.0.0+cu118'

## 1. Simple CPU Example

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y

print(z) 
print(z.size()) 

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


## 2. Simple GPU Example

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([[1,2,3],
                  [4,5,6]], device=device)
y = torch.tensor([[7,8,9],
                  [10,11,12]], device=device)
z = x + y

print(z.size())
print(z.device)

torch.Size([2, 3])
cuda:0


## 3. Moving Tensors CPU & GPU

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x.to(device)
y.to(device)

z = x + y
z.to("cpu")

tensor([[ 8, 10, 12],
        [14, 16, 18]])

## 4. Tensors 생성

In [23]:
import numpy 

w1 = torch.tensor([1,2,3])
w2 = torch.tensor((1,2,3)) 
w3 = torch.tensor(numpy.array([1,2,3])) 

print(w1, w2, w3)

tensor([1, 2, 3]) tensor([1, 2, 3]) tensor([1, 2, 3])


In [24]:
w4 = torch.empty(3,3) 
w5 = torch.zeros(4,4) 
w6 = torch.ones(5,5) 

print(w4, w5, w6)
print(w4.shape, w5.shape, w6.shape) 

tensor([[ 2.9028e+03,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.5262e+03,  0.0000e+00, -2.0740e+00]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([3, 3]) torch.Size([4, 4]) torch.Size([5, 5])


In [25]:
w7 = torch.rand(4,4)   
w8 = torch.randn(4,4)   
w9 = torch.randint(4, 10, (4,4)) 
print(w7, w8, w9)

tensor([[0.7873, 0.9457, 0.2063, 0.2189],
        [0.0711, 0.7495, 0.6047, 0.8292],
        [0.8950, 0.8827, 0.7672, 0.5837],
        [0.0572, 0.7463, 0.2659, 0.2631]]) tensor([[-7.4460e-01, -1.0821e-03,  5.9290e-01, -1.2447e+00],
        [ 4.0354e-01, -3.8229e-01, -6.3586e-01,  1.1782e-01],
        [-1.0029e+00,  2.7857e-01,  9.4938e-01, -2.9474e-01],
        [-1.3951e-01,  2.4834e+00, -2.2960e-01, -3.7797e-01]]) tensor([[7, 7, 7, 8],
        [4, 9, 9, 4],
        [6, 8, 4, 7],
        [7, 8, 9, 6]])


In [26]:
w10 = torch.empty((3,4), dtype=torch.float64, 
                device="cuda")

x = torch.empty_like(w10)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)

## 6. Torch Tensors 데이터 타입

In [27]:
w11 = torch.tensor([1,2,3], 
                   dtype=torch.float32)

w12 = w11.int()   # w changes to int32 after cast

print(w11, w12)

tensor([1., 2., 3.]) tensor([1, 2, 3], dtype=torch.int32)


In [28]:
w13 = w11.to(torch.float64) 
w14 = w11.to(dtype=torch.float64) 

print(w13, w14)

tensor([1., 2., 3.], dtype=torch.float64) tensor([1., 2., 3.], dtype=torch.float64)


In [29]:
x = torch.tensor([1,2,3], 
                 dtype=torch.int32)
y = torch.tensor([1,2,3], 
                 dtype=torch.float32)

z = x + y
print(z)
print(z.dtype)

tensor([2., 4., 6.])
torch.float32


## 7. Tensor 인덱싱, 슬라이싱

In [30]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])

print(x[1,1])

print(x[1,1].item())

tensor(4)
4


In [31]:
# Slicing
x[:2, 1]
x[x < 5]

tensor([1, 2, 3, 4])

In [32]:
# 전치 transpose
print(x.t())

# view() 함수 = numpy의 reshape()와 동일
x.view((2,4))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [33]:
# stack 함수로 합치기
y = torch.stack((x, x))
print(y)

# unbind로 분리하기
a,b = x.unbind(dim=1)
print(a,b)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


## 8. Automatic Differentiation (Autograd)

In [34]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], 
                  dtype=torch.float, 
                  requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [35]:
f = x.pow(2).sum()
f

tensor(91., grad_fn=<SumBackward0>)

In [36]:
f.backward()
x.grad # df/dx = 2x 

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])